### ISSUE TITLE
Only the first audio track is played correctly

### ISSUE THREAD

**Issue by darabi** [federvieh/selma#16]
Using Selma with the Assimil Croatian (German as base language) MP3 files, I can only hear the first track which I start to play. The next track which should be played automatically doesn't play: I hear a stuttering noise, and the track title is blinking in grey colour. Sometimes the play/pause button also flickers (changing between play and pause very quickly).

Tapping on the pause button and then tapping on play makes the track play correctly, but now the next track shows the same behaviour.

Device: Samsung S6
OS: 5.1.1

**Comment by federvieh** [comment]
Hallo Kambiz,

thanks for the report and the pull request #17. I also heard from another user that it happens on a Samsung S4 mini. So, it might be specific for Samsung devices. I'll have a look at your proposed fix and see if I can get access to a Samsung phone to reproduce it.

Viele Grüße
  Frank

**Comment by loseithere** [comment]
I am experiencing this same issue on the Samsung Note 4.  It used to work, but it seems that the latest Android update has impacted this program.

**Comment by darabi** [comment]
Hi Frank,

thank you for looking into this. I will try `mp.reset()` in `onCompletion()` as you proposed on #17 and get back with the results.


Kambiz

**Comment by federvieh** [comment]
@darabi @loseithere I've created a new alpha version which you can find [here](https://github.com/federvieh/selma/releases/tag/v2.3.0alpha8).

I would highly appreciate if you could check if it this fixes this issue.

**Comment by loseithere** [comment]
I tried this one, and it seemed to break the play back even more.  Previously, it would play the first line (The lesson number), and then get stuck when attempting the dialog.  This time, it got stuck on the lesson number itself.

**Comment by loseithere** [comment]
Actually, the first line works just like the previous version.  I had been accidentally pressing it, which was causing the problem with that line.  However, the second line that is played, or any following line that is selected is broken, just as before.

**Comment by federvieh** [comment]
@loseithere, thanks for the feedback!

@darabi, I assume that this is also the case for you. Could you please try to switch to the issue_16 branch, start it from Android Studio and attach some log info to this issue?

BTW, I tried to reproduce the issue on a Samsung device (S5), but already the official version worked as expected. Very strange.

**Comment by federvieh** [comment]
@loseithere @darabi I had another idea on what might be causing the issue, so [here is another alpha version](https://github.com/federvieh/selma/releases/tag/v2.3.0alpha9). If you could check if this improves anything, this would again be appreciated.

If this still doesn't work, could you please try if setting a short delay (e.g. 5%) helps. To set a delay please click on the clock symbol next to the play icon at the bottom of the screen.

**Comment by loseithere** [comment]
Still giving the same issue.  Will give the Lesson number, and then get stuck on the first line of dialogue.  I tried adjusting the delay, but also to no avail.  I sent you an email through the app of the developer log. Not sure if that will help diagnose the issue.

**Comment by darabi** [comment]
Unfortunately, I have the same result as @loseithere reports on Samsung S6 with Android 5.1.1.

I hope to be able to debug the Issue_16 branch this evening.

**Comment by federvieh** [comment]
I've uploaded a new version. I'm still not sure what is causing the issue, but I'd appreciate if you could give this a try.
https://github.com/federvieh/selma/releases/tag/v2.3.0alpha10

**Comment by loseithere** [comment]
It seems to have further broken things with this fix.  This time it started to play all of the tracks at the same time, and wouldn't stop.

**Comment by federvieh** [comment]
Hmm… That's interesting. Again, it doesn't do that on any of my devices or
I wouldn't have uploaded it. :-/ I wish I could get my hands on one of
these devices. I will try this version on the S5 and see if that one also
behaves like you described to give me a clue on what's going on.

**Comment by darabi** [comment]
In a [comment on my pull request](https://github.com/federvieh/selma/pull/17#issuecomment-197001188), you write about my PR

> that this PR breaks the feature to play back a new text by clicking on it while another track is playing

This is in line with the `IllegalArgumentException` I see in the monitor:

```
03-24 19:28:53.121 10068-10068/com.github.federvieh.selma E/MediaPlayer: attachNewPlayer called in state 16
03-24 19:28:53.131 10068-10068/com.github.federvieh.selma W/LT: Could not set data source or prepare media player file:///storage/emulated/0/music/Assimil-Kroatisch/L001-Croatian%20ASSIMIL/N1.mp3
                                                                java.lang.IllegalStateException
                                                                    at android.media.MediaPlayer._setDataSource(Native Method)
                                                                    at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1319)
                                                                    at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1304)
                                                                    at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1240)
                                                                    at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1160)
                                                                    at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1086)
                                                                    at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1067)
                                                                    at com.github.federvieh.selma.assimillib.LessonPlayer.play(LessonPlayer.java:195)
                                                                    at com.github.federvieh.selma.assimillib.LessonPlayer.handleCommand(LessonPlayer.java:260)
                                                                    at com.github.federvieh.selma.assimillib.LessonPlayer.onStartCommand(LessonPlayer.java:272)
                                                                    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3910)
```

Looking at the [MediaPlayer JavaDoc](http://developer.android.com/reference/android/media/MediaPlayer.html) again, I get the impression that `reset()` should only be called once after construction of a new MP.

After that, it should be sufficient to `stop()` and call `prepareAsync()` again. And the [state diagram](http://developer.android.com/reference/android/media/MediaPlayer.html#StateDiagram) seems to implicate that calling `stop()` brings the MP to the state `Stopped` immediately.

I will test that and update my pull request #17.

**Comment by darabi** [comment]
Before I can do that, I need an explanation what the `LessonPlayer.doCont` boolean indicates. In `PlaybarFragment.onClickListener`, you call `LessonPlayer.play(AssimilLesson lesson, int trackNo, boolean cont, Context ctxt)` as follows:

<pre>
imagePlay.setOnClickListener(new OnClickListener() {

  public void onClick(View v) {
      if (LessonPlayer.isPlaying()) {
        LessonPlayer.stopPlaying(getActivity());
      } else {
        if ((LessonPlayer.getLesson(getActivity()) == null) || (LessonPlayer.getTrackNumber(getActivity()) < 0)) {
          try {
            long lessonId = AssimilDatabase.getCurrentLessons().get(0).getId();
            LessonPlayer.play(AssimilDatabase.getLesson(lessonId, v.getContext()), 0, <b>true</b>, v.getContext());
          } catch (IndexOutOfBoundsException e) {
            //Empty list (e.g. no starred lessons) -> ignore
          }
        } else {
          LessonPlayer.play(LessonPlayer.getLesson(getActivity()), LessonPlayer.getTrackNumber(getActivity()), <b>true</b>, v.getContext());
        }
        if ((LessonPlayer.getLesson(getActivity()) != null) && (LessonPlayer.getTrackNumber(getActivity()) >= 0)) {
          OverlayManager.showPlayOverlay(getActivity());
        }
    }
  }
});
</pre>

What does `doCont` signify?

Thanks

**Comment by federvieh** [comment]
Oh, you're right about MediaPlayer.stop(). I thought I tried that, but I'm
probably wrong. I can also have a look this afternoon.

Nevertheless, doCont is used to indicate if the playback should start at
the previously stored position of the track (e.g. when the user pressed the
pause button) or at the beginning of the track (e.g. when the user selected
a new track).

**Comment by federvieh** [comment]
I looked at the JavaDoc again and one may only call `setDataSource()` when in idle state. And the only way to get there is by calling `reset()`.

@darabi I would appreciate if you could send me logs from Android Studio of what happens from the moment when you start playback to the moment when the stuttering starts (using alpha 9).

**Comment by federvieh** [comment]
I've created a [new alpha version](https://github.com/federvieh/selma/releases/tag/v2.3.0alpha11). After reading some more about Google's MediaPlayer API, it seemed to me that it just is unstable across different devices. I decided to use Google's ExoPlayer instead which looks good to me. Can you please check, if this works for you as well.

The downside of this is, that ExoPlayer (and hence the current alpha version of Selma) only runs on Android 4.1 or newer, whereas Selma was also working on Android 2.2. So, if this works for you, I'll just have to swallow the bitter pill and use MediaPlayer on older devices and Exoplayer an Android 4.1 and newer.

**Comment by loseithere** [comment]
This works perfectly now.  Thanks for putting in all the time to solve
this.

Regards,
Ben

**Comment by federvieh** [comment]
I've now created [a new version](https://github.com/federvieh/selma/releases/tag/v2.3.0alpha12) that also works on older devices.

**Comment by S0R0V0N0N** [comment]
10-13 22:14:49.707 26646-26646/rahulmishra.app.musiac E/MediaPlayer: Should have subtitle controller already set
10-13 22:14:49.707 26646-26646/rahulmishra.app.musiac E/MediaPlayer: prepareAsync called in state 8
10-13 22:14:49.812 26646-26646/rahulmishra.app.musiac E/MediaPlayer: Should have subtitle controller already set
10-13 22:14:52.685 26646-26646/rahulmishra.app.musiac E/MediaPlayer: attachNewPlayer called in state 32
first track play well but next trck show obove error
